// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductSearchEngine.Infrastructure.Context;

#nullable disable

namespace ProductSearchEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Refrigerator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tv"
                        });
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Img")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("img");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Price")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tProduct", (string)null);
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.SearchProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SiteId");

                    b.ToTable("SearchProducts");
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.Site", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tSite", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mercado Livre"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Buscapé"
                        });
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.Product", b =>
                {
                    b.HasOne("ProductSearchEngine.Domain.Eitities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.SearchProduct", b =>
                {
                    b.HasOne("ProductSearchEngine.Domain.Eitities.Product", "Product")
                        .WithMany("SearchProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductSearchEngine.Domain.Eitities.Site", "Site")
                        .WithMany("SearchProducts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.Product", b =>
                {
                    b.Navigation("SearchProducts");
                });

            modelBuilder.Entity("ProductSearchEngine.Domain.Eitities.Site", b =>
                {
                    b.Navigation("SearchProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
